# Copyright (C) 2001-2018, Python Software Foundation
# For licence information, see README file.
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-03-23 18:39+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: FRENCH <traductions@lists.afpy.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Exceptions"

#: library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr ""

#: library/asyncio-exceptions.rst:16
#, fuzzy
msgid ""
"A deprecated alias of :exc:`TimeoutError`, raised when the operation has "
"exceeded the given deadline."
msgstr "L'opération a dépassé le délai donné."

#: library/asyncio-exceptions.rst:21
msgid "This class was made an alias of :exc:`TimeoutError`."
msgstr ""

#: library/asyncio-exceptions.rst:26
msgid "The operation has been cancelled."
msgstr ""

#: library/asyncio-exceptions.rst:28
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""

#: library/asyncio-exceptions.rst:34
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ""

#: library/asyncio-exceptions.rst:39
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ""

#: library/asyncio-exceptions.rst:41
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""

#: library/asyncio-exceptions.rst:47
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""

#: library/asyncio-exceptions.rst:50
msgid "A subclass of :exc:`RuntimeError`."
msgstr ""

#: library/asyncio-exceptions.rst:55
msgid "The requested read operation did not complete fully."
msgstr ""

#: library/asyncio-exceptions.rst:57
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr ""

#: library/asyncio-exceptions.rst:59
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr ""

#: library/asyncio-exceptions.rst:63
msgid "The total number (:class:`int`) of expected bytes."
msgstr ""

#: library/asyncio-exceptions.rst:67
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""

#: library/asyncio-exceptions.rst:72
msgid "Reached the buffer size limit while looking for a separator."
msgstr ""

#: library/asyncio-exceptions.rst:74
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr ""

#: library/asyncio-exceptions.rst:78
msgid "The total number of to be consumed bytes."
msgstr ""
